language: python
sudo: false
python:
  - "2.6"
  - "2.7"
addons:
  apt:
    packages:
      - python-matplotlib
      - python-mysqldb
      - python-numpy
      - python-qt4
      - python-qt4-gl
      - python-qt4-sql
      - python-scipy
      - python-vtk
      - python-xlrd
      - python-xlwt
      - zip
      - unzip
      - xvfb
      - python-rpy2
      - python-zmq
      - python-zsi
install:
  - virtualenv --system-site-packages venv && source venv/bin/activate
  - pip install -U pip wheel setuptools
  - pip install -r requirements.txt
  - pip install "$(pwd)"
script:
  - cd /tmp && xvfb-run --server-args="-screen 0 1024x768x16" python -m vistrails.tests -V 1
