language: python
sudo: required
dist: trusty
python:
  - "3.5"
addons:
  apt:
    packages:
#      - python3-matplotlib
#      - python-mysqldb
#      - python3-numpy
#      - python3-pyqt5
#      - python3-pyqt5.qtopengl
#      - python3-pyqt5.qtsql
#      - python3-pyqt5.qtsvg
#      - python3-pyqt5.qtxmlpatterns
#      - python3-pyqt5.qtwebkit
#      - python3-scipy
#      - python-vtk
#      - python3-xlrd
#      - python-xlwt
      - zip
      - unzip
      - xvfb
#      - python3-rpy2
# python3-zmq is needed by parallelflow, but Travis has a bug right now (2015-01-12)
install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
# Useful for debugging any issues with conda
  - conda info -a

#conda install -c https://conda.anaconda.org/mmcauliffe pyqt5
  - conda config --add channels https://conda.anaconda.org/mmcauliffe
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION pyqt5 matplotlib numpy scipy xlrd xlwt qtconsole ipykernel ipython scikit-learn paramiko sqlalchemy python-dateutil mako docutils nose

  - source activate test-environment
# FIXME: What installs qt4?
  - conda uninstall qt

  - pip install -r requirements.txt
  - pip install "$(pwd)"

script:
  - cd /tmp && xvfb-run --server-args="-screen 0 1024x768x16" python -m vistrails.tests -V 1
