language: python
sudo: false
python:
  - "3.4"
  - "3.5"
addons:
  apt:
    packages:
      - python3-matplotlib
#      - python-mysqldb
      - python3-numpy
      - python3-pyqt5
      - python3-pyqt5.qtopengl
      - python3-pyqt5.qtsql
      - python3-pyqt5.qtsvg
      - python3-pyqt5.qtxmlpatterns
      - python3-pyqt5.qtwebkit
      - python3-scipy
#      - python-vtk
      - python3-xlrd
#      - python-xlwt
      - zip
      - unzip
      - xvfb
#      - python3-rpy2
# python3-zmq is needed by parallelflow, but Travis has a bug right now (2015-01-12)
install:
  - virtualenv --system-site-packages venv && source venv/bin/activate
  - pip install -U pip wheel setuptools
  - pip install -r requirements.txt
  - pip install "$(pwd)"
script:
  - cd /tmp && xvfb-run --server-args="-screen 0 1024x768x16" python -m vistrails.tests -V 1
