language: python
sudo: false
python:
  - "2.6"
  - "2.7"
addons:
  apt:
    packages:
# Might be needed for pyqt to work:
#      - libqt4-network
#      - libqt4-svg
#      - libqt4-xmlpatterns
#      - libqtgui4
#      - libqtwebkit4
#      - libqtcore4
      - xvfb
install:
  - curl -Lo miniconda.sh https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh && bash miniconda.sh -b -p $HOME/conda
  - export PATH="$HOME/conda/bin:$PATH" && hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda && conda info -a

  - conda config --add channels vida-nyu
  - conda config --add channels remram
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION pyqt matplotlib numpy scipy vtk xlrd xlwt
  - conda install --channel r rpy2
  - source activate test-environment
  - pip install -r requirements.txt
  - pip install "$(pwd)"
script:
  - cd /tmp && xvfb-run --server-args="-screen 0 1024x768x16" python -m vistrails.tests -V 1
